import 'package:flutter/material.dart';
import 'package:lucide_icons/lucide_icons.dart';

Color? hexToColor(String? hex) {
  if (hex == null || hex.isEmpty) return null;
  String hexColor = hex.toUpperCase().replaceAll("#", "");
  if (hexColor.length == 6) {
    hexColor = "FF$hexColor"; // add alpha if not present
  }
  if (hexColor.length == 8) {
    return Color(int.parse("0x$hexColor"));
  }
  return null;
}

IconData getIconFromString(String? iconName) {
  switch (iconName) {
    // Navigation & Layout
    case 'MessageSquare':
      return LucideIcons.messageSquare;
    case 'BookOpen':
      return LucideIcons.bookOpen;
    case 'LayoutDashboard':
      return LucideIcons.layoutDashboard;
    case 'Book':
      return LucideIcons.book;
    case 'User':
      return LucideIcons.user;
    case 'Search':
      return LucideIcons.search;
    case 'Folder':
      return LucideIcons.folder;
    case 'FileText':
      return LucideIcons.fileText;
    case 'SidebarOpen':
      return LucideIcons.panelRightOpen;
    case 'SidebarClose':
      return LucideIcons.panelRightClose;
    case 'LayoutGrid':
      return LucideIcons.layoutGrid;
    case 'LayoutList':
      return LucideIcons.layoutList;
    case 'LayoutTemplate':
      return LucideIcons.layout;
    case 'Rows':
      return LucideIcons.rows;
    case 'Home':
      return LucideIcons.home;
    case 'Settings':
      return LucideIcons.settings;
    case 'Menu':
      return LucideIcons.menu;
    case 'Grid':
      return LucideIcons.grid;
    case 'List':
      return LucideIcons.list;
    case 'Calendar':
      return LucideIcons.calendar;
    case 'Clock':
      return LucideIcons.clock;
    // User & Authentication
    case 'Building':
      return LucideIcons.building;
    case 'Users':
      return LucideIcons.users;
    case 'UserPlus':
      return LucideIcons.userPlus;
    case 'UserCheck':
      return LucideIcons.userCheck;
    case 'UserCog':
      return LucideIcons.userCog;
    case 'UserX':
      return LucideIcons.userX;
    case 'UserCircle':
      return LucideIcons.userCircle;
    case 'UserCircle2':
      return LucideIcons.userCircle2;
    case 'Shield':
      return LucideIcons.shield;
    case 'ShieldAlert':
      return LucideIcons.shieldAlert;
    case 'ShieldCheck':
      return LucideIcons.shieldCheck;
    case 'Key':
      return LucideIcons.key;
    case 'KeyRound':
      return LucideIcons.keyRound;
    case 'Lock':
      return LucideIcons.lock;
    case 'Unlock':
      return LucideIcons.unlock;
    case 'Fingerprint':
      return LucideIcons.fingerprint;
    // E-commerce & Shipping
    case 'Package':
      return LucideIcons.package;
    case 'Package2':
      return LucideIcons.package2;
    case 'PackagePlus':
      return LucideIcons.packagePlus;
    case 'PackageCheck':
      return LucideIcons.packageCheck;
    case 'PackageX':
      return LucideIcons.packageX;
    case 'Truck':
      return LucideIcons.truck;
    case 'Warehouse':
      return LucideIcons.warehouse;
    case 'Store':
      return LucideIcons.store;
    case 'Shop':
      return LucideIcons.store;
    case 'Tag':
      return LucideIcons.tag;
    case 'Tags':
      return LucideIcons.tags;
    case 'Bookmark':
      return LucideIcons.bookmark;
    case 'Gift':
      return LucideIcons.gift;
    // case 'Barcode': return LucideIcons.barcode; // Not available in lucide_icons
    // Devices & Communication
    case 'Monitor':
      return LucideIcons.monitor;
    case 'Laptop':
      return LucideIcons.laptop;
    case 'Tablet':
      return LucideIcons.tablet;
    case 'Smartphone':
      return LucideIcons.smartphone;
    case 'HardDrive':
      return LucideIcons.hardDrive;
    case 'Mail':
      return LucideIcons.mail;
    case 'MailOpen':
      return LucideIcons.mailOpen;
    case 'Send':
      return LucideIcons.send;
    case 'Phone':
      return LucideIcons.phone;
    case 'PhoneCall':
      return LucideIcons.phoneCall;
    case 'PhoneOutgoing':
      return LucideIcons.phoneOutgoing;
    case 'PhoneIncoming':
      return LucideIcons.phoneIncoming;
    case 'Headphones':
      return LucideIcons.headphones;
    case 'Speaker':
      return LucideIcons.speaker;
    case 'Battery':
      return LucideIcons.battery;
    case 'BatteryCharging':
      return LucideIcons.batteryCharging;
    case 'Wifi':
      return LucideIcons.wifi;
    case 'Bluetooth':
      return LucideIcons.bluetooth;
    case 'MessageCircle':
      return LucideIcons.messageCircle;
    case 'Bell':
      return LucideIcons.bell;
    case 'AlertTriangle':
      return LucideIcons.alertTriangle;
    case 'FileSpreadsheet':
      return LucideIcons.fileSpreadsheet;
    case 'FileImage':
      return LucideIcons.fileImage;
    case 'Download':
      return LucideIcons.download;
    case 'Upload':
      return LucideIcons.upload;
    case 'Printer':
      return LucideIcons.printer;
    // Finance & Analytics
    case 'DollarSign':
      return LucideIcons.dollarSign;
    case 'Landmark':
      return LucideIcons.landmark;
    case 'CreditCard':
      return LucideIcons.creditCard;
    case 'Receipt':
      return LucideIcons.receipt;
    case 'Calculator':
      return LucideIcons.calculator;
    case 'Percent':
      return LucideIcons.percent;
    case 'TrendingUp':
      return LucideIcons.trendingUp;
    case 'TrendingDown':
      return LucideIcons.trendingDown;
    case 'BarChart':
      return LucideIcons.barChart;
    case 'BarChart2':
      return LucideIcons.barChart2;
    case 'BarChart3':
      return LucideIcons.barChart3;
    case 'BarChart4':
      return LucideIcons.barChart4;
    case 'LineChart':
      return LucideIcons.lineChart;
    case 'PieChart':
      return LucideIcons.pieChart;
    case 'CandlestickChart':
      return LucideIcons.candlestickChart;
    case 'Bot':
      return LucideIcons.bot;
    case 'Layout':
      return LucideIcons.layout;
    case 'File':
      return LucideIcons.file;
    case 'BadgeCheck':
      return LucideIcons.badgeCheck;
    case 'Contact':
      return LucideIcons.contact;
    case 'UserMinus':
      return LucideIcons.userMinus;
    case 'Briefcase':
      return LucideIcons.briefcase;
    case 'Wallet':
      return LucideIcons.wallet;
    case 'Banknote':
      return LucideIcons.banknote;
    case 'Coins':
      return LucideIcons.coins;
    case 'ShoppingCart':
      return LucideIcons.shoppingCart;
    case 'Boxes':
      return LucideIcons.boxes;
    case 'ClipboardList':
      return LucideIcons.clipboardList;
    case 'Cpu':
      return LucideIcons.cpu;
    case 'Server':
      return LucideIcons.server;
    case 'Terminal':
      return LucideIcons.terminal;
    case 'Code2':
      return LucideIcons.code2;
    case 'Bug':
      return LucideIcons.bug;
    // Development & Technology
    case 'Database':
      return LucideIcons.database;
    case 'GitBranch':
      return LucideIcons.gitBranch;
    case 'GitFork':
      return LucideIcons.gitFork;
    case 'GitPullRequest':
      return LucideIcons.gitPullRequest;
    case 'Code':
      return LucideIcons.code;
    case 'TerminalSquare':
      return LucideIcons.terminalSquare;
    case 'Webhook':
      return LucideIcons.webhook;
    case 'ServerCrash':
      return LucideIcons.serverCrash;
    case 'Cloud':
      return LucideIcons.cloud;
    case 'CloudOff':
      return LucideIcons.cloudOff;
    case 'CloudRain':
      return LucideIcons.cloudRain;
    case 'CloudSnow':
      return LucideIcons.cloudSnow;
    case 'CloudLightning':
      return LucideIcons.cloudLightning;
    case 'Activity':
      return LucideIcons.activity;
    case 'Chip':
      return LucideIcons.cpu;
    case 'BrainCircuit':
      return LucideIcons.brainCircuit;
    case 'Rocket':
      return LucideIcons.rocket;
    case 'Wand2':
      return LucideIcons.wand2;
    case 'Flame':
      return LucideIcons.flame;
    case 'Camera':
      return LucideIcons.camera;
    case 'Image':
      return LucideIcons.image;
    case 'Eye':
      return LucideIcons.eye;
    case 'EyeOff':
      return LucideIcons.eyeOff;
    case 'Globe':
      return LucideIcons.globe;
    case 'MapPin':
      return LucideIcons.mapPin;
    case 'Compass':
      return LucideIcons.compass;
    case 'Star':
      return LucideIcons.star;
    case 'Trash':
      return LucideIcons.trash;
    case 'Edit':
      return LucideIcons.edit;
    case 'Plus':
      return LucideIcons.plus;
    case 'Minus':
      return LucideIcons.minus;
    case 'X':
      return LucideIcons.x;
    case 'Check':
      return LucideIcons.check;
    case 'ChevronDown':
      return LucideIcons.chevronDown;
    case 'ChevronUp':
      return LucideIcons.chevronUp;
    case 'ChevronLeft':
      return LucideIcons.chevronLeft;
    case 'ChevronRight':
      return LucideIcons.chevronRight;
    case 'Info':
      return LucideIcons.info;
    case 'HelpCircle':
      return LucideIcons.helpCircle;
    case 'ExternalLink':
      return LucideIcons.externalLink;
    case 'ClipboardCheck':
      return LucideIcons.clipboardCheck;
    case 'QrCode':
      return LucideIcons.qrCode;
    // Modern Interface Elements
    case 'ArrowUpRight':
      return LucideIcons.arrowUpRight;
    case 'ArrowDownLeft':
      return LucideIcons.arrowDownLeft;
    case 'ArrowUpDown':
      return LucideIcons.arrowUpDown;
    case 'ArrowLeftRight':
      return LucideIcons.arrowLeftRight;
    case 'MoveUpRight':
      return LucideIcons.moveUpRight;
    case 'MoveDownLeft':
      return LucideIcons.moveDownLeft;
    case 'Maximize':
      return LucideIcons.maximize;
    case 'Minimize':
      return LucideIcons.minimize;
    case 'Expand':
      return LucideIcons.expand;
    case 'Shrink':
      return LucideIcons.shrink;
    case 'Refresh':
      return LucideIcons.refreshCcw;
    case 'RefreshCw':
      return LucideIcons.refreshCw;
    case 'RotateCw':
      return LucideIcons.rotateCw;
    case 'RotateCcw':
      return LucideIcons.rotateCcw;
    case 'Loader':
      return LucideIcons.loader;
    case 'Loader2':
      return LucideIcons.loader2;
    case 'Filter':
      return LucideIcons.filter;
    case 'Settings2':
      return LucideIcons.settings2;
    case 'Sliders':
      return LucideIcons.sliders;
    case 'ToggleLeft':
      return LucideIcons.toggleLeft;
    case 'ToggleRight':
      return LucideIcons.toggleRight;
    case 'SlidersHorizontal':
      return LucideIcons.slidersHorizontal;
    default:
      return LucideIcons.barChart4;
  }
}
